[project]
name = "lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "saacostam", email = "73088662+saacostam@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.142.1",
    "openai>=3.27.0",
    "pyjwt>=2.15.1",
]

[project.scripts]
lab = "lab:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-mock>=3.16.0",
    "ruff>=0.16.9",
    "taskipy>=1.14.1",
]

[tool.taskipy.tasks]
lint = "uv run ruff check --fix ."
format = "uv run ruff format ."
typecheck = "uv run mypy ."
test = "uv run pytest"
# You can even chain commands together like npm scripts
validate = "task lint && task format && task typecheck && task test"

[tool.pytest.ini_options]
testpaths = ["src"]
asyncio_mode = "auto"
addopts = ["--import-mode=importlib"]

[tool.fastapi]
entrypoint = "lab.main:app"

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query"]
