from typing import Protocol

from .todo import Todo


class TodoRepository(Protocol):
    async def create(self, todo: Todo) -> Todo: ...
    async def get_by_id(self, id: str) -> Todo | None: ...
    async def remove(self, id: str) -> str: ...
    async def update(self, id: str, todo: Todo) -> Todo: ...
