from typing import Protocol

from .todo import Todo


class TodoRepository(Protocol):
    def create(self, todo: Todo) -> Todo: ...
    def get_by_id(self, id: str) -> Todo | None: ...
    def remove(self, id: str) -> str: ...
    def update(self, id: str, todo: Todo) -> Todo: ...
