from typing import Protocol

from .though import ChainOfThough, LeanChainOfThough


class ChainOfThoughRepository(Protocol):
    async def create(self, cot: ChainOfThough) -> ChainOfThough: ...
    async def get_all_by_chat_id(self, chat_id: str) -> list[LeanChainOfThough]: ...
    async def get_by_id(self, id: str) -> ChainOfThough | None: ...
    async def remove(self, chain_id: str) -> str: ...
    async def update(self, chain_id: str, cot: ChainOfThough) -> ChainOfThough: ...
