from typing import Protocol

from .though import ChainOfThough, LeanChainOfThough


class ChainOfThoughRepository(Protocol):
    async def create(self, chat: ChainOfThough) -> ChainOfThough: ...
    async def get_all_by_chat_id(self, user_id: str) -> list[LeanChainOfThough]: ...
    async def get_by_id(self, id: str) -> ChainOfThough: ...
    async def remove(self, id: str) -> str: ...
    async def update(self, chat: ChainOfThough) -> ChainOfThough: ...
