from typing import Protocol

from .though import ChainOfThought, LeanChainOfThought


class ChainOfThoughtRepository(Protocol):
    async def create(self, cot: ChainOfThought) -> ChainOfThought: ...
    async def get_all_by_chat_id(self, chat_id: str) -> list[LeanChainOfThought]: ...
    async def get_by_id(self, id: str) -> ChainOfThought | None: ...
    async def remove(self, chain_id: str) -> str: ...
    async def update(self, chain_id: str, cot: ChainOfThought) -> ChainOfThought: ...
