from typing import Protocol

from .chat import Chat, LeanChat


class ChatRepository(Protocol):
    async def create(self, chat: Chat) -> Chat: ...
    async def get_by_id(self, id: str) -> Chat | None: ...
    async def get_all_by_user_id(self, user_id: str) -> list[LeanChat]: ...
    async def remove(self, id: str) -> str: ...
    async def update(self, chat_id: str, chat: Chat) -> Chat: ...
